version: '3.7'

services:
  testsolution-blazor:
    image: company/testsolution-blazor:latest
    container_name: testsolution-blazor
    build:
      context: ../../
      dockerfile: src/Company.TestSolution.Blazor/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - App__SelfUrl=https://localhost:44307
      - AuthServer__RequireHttpsMetadata=false  
      - AuthServer__Authority=http://testsolution-identity-server      
      - RemoteServices__AbpAccountPublic__BaseUrl=https://localhost:44334
      - RemoteServices__Default__BaseUrl=https://localhost:44354
    ports:
      - "44307:443"
    depends_on:
      - testsolution-api
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  testsolution-api:
    image: company/testsolution-api:latest
    container_name: testsolution-api
    build:
      context: ../../
      dockerfile: src/Company.TestSolution.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - App__SelfUrl=https://localhost:44354
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__SetSelfAsIssuer=true
      - AuthServer__Authority=http://testsolution-identity-server
      - App__MVCPublicUrl=https://localhost:44306
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=TestSolution;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;Persist Security Info=True;
      - Redis__Configuration=redis
    ports:
      - "44354:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  
  testsolution-identity-server:
    image: company/testsolution-identityserver:latest
    container_name: testsolution-identity-server
    build:
      context: ../../
      dockerfile: src/Company.TestSolution.IdentityServer/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - App__SelfUrl=https://localhost:44334
      - App_CorsOrigins=https://localhost:44307
      - App_RedirectAllowedUrls=https://localhost:44307
      - AuthServer__Authority=http://testsolution-identity-server
      - AuthServer__RequireHttpsMetadata=false
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=TestSolution;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;Persist Security Info=True;
      - Redis__Configuration=redis
    ports:
      - "44334:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  db-migrator:
    image: company/testsolution-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/TestSolution.DbMigrator/Dockerfile.local
    environment:
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=TestSolution;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;Persist Security Info=True;
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network    
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network  
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network  
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      

volumes:
  sqldata:
    name: testsolution_sqldata
networks:
  abp-network:
    name: testsolution-network
    driver: bridge